// <auto-generated />
using System;
using BKeeper.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BKeeper.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BKeeperDbContext))]
    partial class BKeeperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BKeeper.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssignedRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Family")
                        .HasColumnType("integer");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("OutcomeNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SnoozeUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("BoxId", "Fingerprint");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SessionId");

                    b.HasIndex("BoxId", "ExternalId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ClassSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoachName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Window")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("WorkoutId");

                    b.HasIndex("BoxId", "ExternalId");

                    b.ToTable("ClassSessions");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "Name");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.EvaluationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "Key")
                        .IsUnique();

                    b.ToTable("EvaluationForms");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.EvaluationFormLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("EvaluationFormLinks");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.EvaluationResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scores")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("MemberId");

                    b.ToTable("EvaluationResponses");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BaselineValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("BoxId", "ExternalId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalProgresses");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.HealthScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("CalculationDate")
                        .HasColumnType("date");

                    b.Property<int>("ConfigVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Factors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("InsufficientData")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<int>("SessionCount")
                        .HasColumnType("integer");

                    b.Property<int>("TenureDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "MemberId", "CalculationDate")
                        .IsUnique();

                    b.ToTable("HealthScores");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.HealthScoreConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AttendanceEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("AttendanceWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("AttendanceWindowDays")
                        .HasColumnType("integer");

                    b.Property<bool>("BookingBehaviourEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("BookingBehaviourWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("BookingBehaviourWindowDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsistencyEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("ConsistencyWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("ConsistencyWindowWeeks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("EngagementEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("EngagementWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("EngagementWindowDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MinSessions")
                        .HasColumnType("integer");

                    b.Property<int>("MinTenureDays")
                        .HasColumnType("integer");

                    b.Property<bool>("ProgressEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("ProgressWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("ProgressWindowDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "IsActive");

                    b.HasIndex("BoxId", "Version")
                        .IsUnique();

                    b.ToTable("HealthScoreConfigurations");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ImportRowError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("Sheet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.ToTable("ImportRowErrors");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BookingsUpserted")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FreezesUpserted")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsUpserted")
                        .HasColumnType("integer");

                    b.Property<string>("MappingProfile")
                        .HasColumnType("text");

                    b.Property<int>("MembersUpserted")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipsUpserted")
                        .HasColumnType("integer");

                    b.Property<int>("NotesUpserted")
                        .HasColumnType("integer");

                    b.Property<int>("RowErrorCount")
                        .HasColumnType("integer");

                    b.Property<int>("SessionsUpserted")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AwayUntil")
                        .HasColumnType("date");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CancelDate")
                        .HasColumnType("date");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("InjuryFlagUntil")
                        .HasColumnType("date");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text");

                    b.Property<Guid?>("PrimaryCoachId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "ExternalId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MemberConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "MemberId", "Channel")
                        .IsUnique();

                    b.ToTable("MemberConsents");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MemberNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberNotes");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Baseline26w")
                        .HasColumnType("double precision");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MedianGapDays")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeMix")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsualDays")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UsualWindow")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MemberProfiles");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MemberWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bookings")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FirstVisitDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IsoWeekStart")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastVisitDate")
                        .HasColumnType("date");

                    b.Property<int>("LateCancels")
                        .HasColumnType("integer");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoShows")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visits")
                        .HasColumnType("integer");

                    b.Property<string>("VisitsByType")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VisitsByWindow")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "MemberId", "IsoWeekStart")
                        .IsUnique();

                    b.ToTable("MemberWeeks");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FreezeEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FreezeStart")
                        .HasColumnType("date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MonthlyPriceEur")
                        .HasColumnType("numeric");

                    b.Property<int?>("PlanFreqPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MembershipFreeze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("BoxId", "ExternalId");

                    b.ToTable("MembershipFreezes");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MetricDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aggregation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Limitations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeWindow")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("MetricDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7ebdc5a-d1f9-4678-b10e-c59ec60f3884"),
                            Aggregation = "count",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How many members currently have status Active (plan §5: not frozen, not cancelled).",
                            Formula = "COUNT(Members WHERE Status = Active)",
                            IsActive = true,
                            Key = "active_members",
                            Limitations = "Checks Member.Status only. Plan §5's fuller definition — \"with membership valid on the date\" — would also cross-check Membership start/end and freeze windows, which this count doesn't do yet.",
                            Name = "Active members",
                            TimeWindow = "as of today",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "The denominator behind every other retention rate on the dashboard — new, churned, net change and monthly churn % are all measured against this number."
                        },
                        new
                        {
                            Id = new Guid("609aee5b-e631-4766-a1f0-3e61d70cb42a"),
                            Aggregation = "count",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Members who joined on or after the 1st of this month.",
                            Formula = "COUNT(Members WHERE JoinDate BETWEEN first-of-month AND today)",
                            IsActive = true,
                            Key = "new_members_this_month",
                            Limitations = "\"Today\" and \"first of month\" use UTC, not the box's own time zone (plan D9 says the box's local time zone should govern week/month boundaries) — this can be off by a day around midnight for boxes far from UTC.",
                            Name = "New members this month",
                            TimeWindow = "current calendar month, to date",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "The growth half of Net member change, and the leading indicator for onboarding-track load (plan §6.6)."
                        },
                        new
                        {
                            Id = new Guid("72919d59-aa36-488c-98bb-c918b9850745"),
                            Aggregation = "count",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Members whose CancelDate falls in the current month.",
                            Formula = "COUNT(Members WHERE CancelDate BETWEEN first-of-month AND today)",
                            IsActive = true,
                            Key = "churned_members_this_month",
                            Limitations = "Counts explicit cancellations only. Plan §5's churn definition also includes \"lapsed\" (45+ days with no visit while still marked active) — that group is tracked separately as Lapsed members and is not folded into this count or into the monthly churn rate.",
                            Name = "Churned members this month",
                            TimeWindow = "current calendar month, to date",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Feeds both Net member change and Monthly churn rate."
                        },
                        new
                        {
                            Id = new Guid("5aa46cbe-e1d5-4bd9-a4ae-0540a511daa0"),
                            Aggregation = "difference",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "New members minus churned members this month.",
                            Formula = "new_members_this_month − churned_members_this_month",
                            IsActive = true,
                            Key = "net_member_change",
                            Limitations = "Inherits both inputs' limitations: lapsed members reduce actual active headcount without ever counting as \"churned\" here, so a box with a lot of lapsing (but not cancelling) members will show a healthier net change than its real trajectory.",
                            Name = "Net member change",
                            TimeWindow = "current calendar month, to date",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "The single number that says whether the box is growing or shrinking this month."
                        },
                        new
                        {
                            Id = new Guid("09c6aa59-836b-42df-ac21-c3c685161990"),
                            Aggregation = "rate",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The share of members who were already active before this month and have since cancelled.",
                            Formula = "100 × churned_members_this_month ÷ COUNT(Members WHERE JoinDate < first-of-month AND (CancelDate IS NULL OR CancelDate >= first-of-month))",
                            IsActive = true,
                            Key = "monthly_churn_rate_pct",
                            Limitations = "Same lapsed-vs-cancelled gap as churned_members_this_month: this rate only reflects explicit cancellations, so it understates plan §5's full churn definition in boxes where members go quiet without formally cancelling.",
                            Name = "Monthly churn rate",
                            TimeWindow = "current calendar month, to date",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Plan §13's headline success metric — target is −20% relative after 6 months of the pilot, measured against a Week-0 baseline."
                        },
                        new
                        {
                            Id = new Guid("03e8ac21-d391-47cf-a5f0-831872d22eab"),
                            Aggregation = "count",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Active members who haven't attended a class in 45+ days (plan §5's \"lapsed\" clause of Churned), including active members with no recorded visit at all.",
                            Formula = "COUNT(Members WHERE Status = Active AND (no attended Booking OR days since their most recent attended Booking >= 45))",
                            IsActive = true,
                            Key = "lapsed_members",
                            Limitations = "Computed live at query time rather than stored on the member (docs/DECISIONS.md D24). The 45-day threshold is hardcoded in the dashboard query today rather than read from rule_config, so changing it per box isn't wired up yet.",
                            Name = "Lapsed members",
                            TimeWindow = "as of today, 45-day no-visit threshold",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Catches the members who are functionally gone but haven't cancelled — the group monthly_churn_rate_pct misses."
                        },
                        new
                        {
                            Id = new Guid("f8a4c2bf-971e-4b28-9414-bf7cfc46bd22"),
                            Aggregation = "curve",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "For members who joined in the same calendar month (a \"cohort\"), the share still not cancelled N months later.",
                            Formula = "at month N: COUNT(cohort members WHERE CancelDate IS NULL OR CancelDate >= cohort_month + (N+1) months) ÷ cohort size",
                            IsActive = true,
                            Key = "cohort_retention_curve",
                            Limitations = "\"Retained\" means \"not yet cancelled\", not \"still visiting\" — a frozen or lapsed member who hasn't formally cancelled still counts as retained in this curve. Months with no data yet (not enough time has passed since the cohort joined) show as blank, not zero.",
                            Name = "Cohort retention curve",
                            TimeWindow = "months 0-12 since each cohort's join month",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Shows whether retention by tenure is improving release over release, independent of month-to-month join-volume swings — the standard SaaS/membership retention view."
                        },
                        new
                        {
                            Id = new Guid("0d8bf362-adb0-4200-8b5b-890ce60179a1"),
                            Aggregation = "histogram",
                            Category = "Retention",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How many months members stayed before cancelling, grouped into 1-month buckets up to 24+.",
                            Formula = "for each cancelled member: months between their join month and their CancelDate, bucketed 0-1mo, 1-2mo, ... 24mo+",
                            IsActive = true,
                            Key = "tenure_at_churn_histogram",
                            Limitations = "Only members with a recorded CancelDate appear here; lapsed members who never formally cancelled are excluded, even though plan §5 treats them as churned too.",
                            Name = "Tenure-at-churn histogram",
                            TimeWindow = "all churned members, all-time",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Distinguishes an onboarding problem (a spike in the 0-1/1-2 month buckets) from long-tenure churn — very different fixes."
                        },
                        new
                        {
                            Id = new Guid("33500b4f-b904-483c-b4a1-030c69e47c8c"),
                            Aggregation = "rate",
                            Category = "AlertOps",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Of the alerts that have been claimed or resolved, the share claimed before their SLA due date.",
                            Formula = "100 × COUNT(alerts where the first Claimed event happened on or before Alert.DueAt) ÷ COUNT(alerts that were ever claimed, resolved, or auto-resolved)",
                            IsActive = true,
                            Key = "alert_sla_compliance_rate_pct",
                            Limitations = "An alert that was AutoResolved without ever being claimed lands in the denominator (via its Status) but has no claim timestamp to compare against DueAt, so it can never count as compliant — this slightly understates true SLA performance on boxes with a lot of unassisted returns.",
                            Name = "Alert SLA compliance",
                            TimeWindow = "all-time (not windowed)",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Plan §13's SLA target is ≥90% — a coverage/staffing signal for the alert inbox (plan §6.4's escalation ladder exists specifically to protect this)."
                        },
                        new
                        {
                            Id = new Guid("c93bf8ac-c140-47e8-a6e3-5d8491cf60d4"),
                            Aggregation = "mean",
                            Category = "AlertOps",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "On average, how long an alert sits unclaimed before a coach or manager claims it.",
                            Formula = "mean(first Claimed AlertEvent.CreatedAt − Alert.CreatedAt) in hours, over alerts claimed at least once",
                            IsActive = true,
                            Key = "alert_avg_time_to_claim_hours",
                            Limitations = "Alerts that were never claimed (e.g. auto-resolved before anyone acted) are excluded entirely rather than counted as a very long or infinite claim time, so this can look better than the SLA compliance rate suggests.",
                            Name = "Average time to claim",
                            TimeWindow = "all-time (not windowed)",
                            Unit = "hours",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "A direct read on inbox responsiveness, independent of whether the SLA was technically met."
                        },
                        new
                        {
                            Id = new Guid("42916e16-e0ba-4e8a-a6cc-c4ac99df3332"),
                            Aggregation = "rate",
                            Category = "AlertOps",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Of the alerts that reached a resolved state, the share where the member came back (returned on their own or after being contacted).",
                            Formula = "100 × COUNT(alerts WHERE Status = AutoResolved OR Outcome = 'returned') ÷ COUNT(alerts WHERE Status IN (Resolved, AutoResolved))",
                            IsActive = true,
                            Key = "alert_save_rate_pct",
                            Limitations = "This is not a causal measure: a member marked \"saved\" here may well have returned regardless of any alert or outreach. See alert_return_rate_holdout_vs_treated_pct for the actual causal comparison plan §13 asks for.",
                            Name = "Save rate",
                            TimeWindow = "all-time (not windowed)",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Plan §13's \"Save rate\" — the headline number for whether the alert/outreach loop is working."
                        },
                        new
                        {
                            Id = new Guid("559b3a5b-c7ff-4ee2-b621-f2e2145c6a4c"),
                            Aggregation = "rate",
                            Category = "AlertOps",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Of members who received (or were held out from) an automated outreach message, the share who attended a class within 14 days afterwards — shown separately for the 10% random holdout group and the treated (message actually sent) group.",
                            Formula = "100 × COUNT(recipients with an attended Booking within 14 days of the Outreach) ÷ COUNT(recipients), computed once with IsHoldout = true and once with IsHoldout = false",
                            IsActive = true,
                            Key = "alert_return_rate_holdout_vs_treated_pct",
                            Limitations = "Only covers system-sent outreach (Outreach.SentBy = System) — coach-sent messages skip the holdout gate (plan §6.5) entirely and aren't part of this comparison. Returns no value for a group until it has at least one recipient to divide by.",
                            Name = "Outreach return rate — holdout vs treated",
                            TimeWindow = "per system outreach, next 14 days",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Plan §13's causal check: without comparing against a holdout, \"the alert saved this member\" is unprovable, since many flagged members return on their own anyway."
                        },
                        new
                        {
                            Id = new Guid("6789264c-5dd6-4c68-b1a4-daf9f5535f63"),
                            Aggregation = "mean",
                            Category = "Attendance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A member's normal weekly attendance rate, used as the reference point their recent activity is compared against.",
                            Formula = "mean(attended visits per ISO week), over weeks that start between 26 weeks and 4 weeks before the snapshot date",
                            IsActive = true,
                            Key = "member_baseline_visits_per_week",
                            Limitations = "Plan §5 also requires at least 8 weeks of post-join history before trusting a baseline (\"min 8 weeks\") — the current calculation doesn't enforce that minimum, so a very new member's baseline can be built from very few weeks of data. The seasonal August/Christmas dampening that exists as AttendanceMetrics.ApplySeasonalFactor is not applied inside this calculation.",
                            Name = "Baseline visits per week",
                            TimeWindow = "weeks −26 to −4 relative to the snapshot date",
                            Unit = "visits/week",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Plan §5's \"Baseline rate\" — the number R01 (absence gap), R02 (not booking) and R03 (frequency drop) all gate on before evaluating a member, so a naturally low-frequency member isn't flagged for being naturally low-frequency."
                        },
                        new
                        {
                            Id = new Guid("8996b77c-a7dc-4dd1-9457-f74fb327532e"),
                            Aggregation = "ratio",
                            Category = "Attendance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How a member's attendance over the last two weeks compares to their own usual rate.",
                            Formula = "(attended visits in the last 14 days ÷ 2) ÷ member_baseline_visits_per_week",
                            IsActive = true,
                            Key = "member_recent_attendance_ratio",
                            Limitations = "Only computed (and only shown) once BaselinePerWeek clears the rule's configured minimum (1.5/week by default); below that, R03 skips the member entirely rather than showing a misleadingly volatile ratio.",
                            Name = "Recent attendance ratio (2-week vs baseline)",
                            TimeWindow = "last 14 days vs the 26-week baseline",
                            Unit = "ratio",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "This ratio is R03's frequency-drop trigger — amber below 60% of baseline, red below 30% by default (box-configurable) — the earliest attendance-based warning signal in the rule catalogue."
                        },
                        new
                        {
                            Id = new Guid("5a4427d9-1552-4db7-b1c9-86976cf0beba"),
                            Aggregation = "rate",
                            Category = "Attendance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The share of a member's bookings in the last 8 weeks that ended in a no-show or a too-late cancellation, rather than an attended visit.",
                            Formula = "COUNT(Bookings in last 8 weeks WHERE Status IN (NoShow, LateCancel)) ÷ COUNT(Bookings in last 8 weeks), only evaluated when there are at least 6 bookings in that window",
                            IsActive = true,
                            Key = "member_no_show_rate_8w",
                            Limitations = "No-shows and late-cancels are combined into one rate; there is no separately computed figure for late-cancels alone, or for ordinary advance cancellations (BookingStatus.Cancelled), even though the booking model tracks all three statuses separately.",
                            Name = "No-show / late-cancel rate (8 weeks)",
                            TimeWindow = "last 8 weeks",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "This is what BKeeper calls the no-show rate (it's also the closest thing to a \"cancellation rate\" the app computes today) — it's R04's rate trigger (>25% by default) and flags members who keep booking but not showing."
                        },
                        new
                        {
                            Id = new Guid("622c1ab7-619b-4e9b-87a4-681395725e7d"),
                            Aggregation = "median",
                            Category = "Attendance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The typical number of days a member goes between one attended class and the next.",
                            Formula = "median(days between consecutive attended-visit dates), over visits in the last 84 days",
                            IsActive = true,
                            Key = "member_median_gap_days",
                            Limitations = "Needs at least 2 visits in the 12-week window to produce a value; with 0 or 1 visits it's null, and R01 falls back to its configured min_days default instead of a member-specific threshold.",
                            Name = "Median gap between visits",
                            TimeWindow = "last 12 weeks (84 days)",
                            Unit = "days",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Plan §5's \"Median gap\" exactly — R01's absence-gap threshold is built directly from it (min_days, or this value × a multiplier, whichever is larger)."
                        },
                        new
                        {
                            Id = new Guid("6ca33336-fcfa-412a-bad0-0fbe58423329"),
                            Aggregation = "median",
                            Category = "Attendance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The typical number of days a member goes between one booking and the next (booking date, not visit date).",
                            Formula = "median(days between consecutive Booking.BookedAt dates), over bookings in the last 84 days",
                            IsActive = true,
                            Key = "member_median_booking_gap_days",
                            Limitations = "Same as member_median_gap_days: null with fewer than 2 bookings in the window, and R02 falls back to its configured min_days default.",
                            Name = "Median gap between bookings",
                            TimeWindow = "last 12 weeks (84 days)",
                            Unit = "days",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Feeds R02's not-booking threshold, the same way member_median_gap_days feeds R01."
                        },
                        new
                        {
                            Id = new Guid("6b5ef895-60a2-4982-aba5-11db77b07bd3"),
                            Aggregation = "heatmap",
                            Category = "Workouts",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How the box's attended visits break down by day of week, class time window (Early/Morning/Lunch/Afternoon/Evening) and workout type.",
                            Formula = "COUNT(attended Bookings in the last 84 days), grouped by (DayOfWeek, ClassSession.Window, the class's dominant WorkoutTag)",
                            IsActive = true,
                            Key = "workout_window_type_mix",
                            Limitations = "Plan §5 defines \"Usual window\" and \"Type mix\" per member (the mode of one member's own visit windows in weeks −16..−4, and their own workout-type distribution), which needs MemberProfile — not populated yet (docs/DECISIONS.md D24). This heatmap aggregates every member together as the closest thing currently computed; it is not the per-member figure the plan describes, and it isn't used by any rule (R05/R06/R07, which need the per-member version, aren't built).",
                            Name = "Window × type mix (box-level)",
                            TimeWindow = "last 12 weeks (84 days)",
                            Unit = "count",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Surfaces underused time slots and shifting workout-type popularity across the whole box — feeds the workout-mix dashboard."
                        },
                        new
                        {
                            Id = new Guid("dceecc84-5d24-4728-a88c-0e633c42f811"),
                            Aggregation = "mean",
                            Category = "Workouts",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How full classes typically run, by class type and time window.",
                            Formula = "100 × mean(COUNT(Bookings WHERE Status != Cancelled) ÷ ClassSession.Capacity), grouped by (ClassType, Window), over sessions in the last 84 days with a capacity set",
                            IsActive = true,
                            Key = "class_fill_rate_pct",
                            Limitations = "No-shows and late-cancels still count toward the numerator (only Cancelled bookings are excluded), so this measures booked fill, not who actually showed up. Sessions without a Capacity value are skipped entirely rather than treated as unlimited.",
                            Name = "Class fill rate",
                            TimeWindow = "last 12 weeks (84 days)",
                            Unit = "percent",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1,
                            WhyItMatters = "Identifies over- or under-booked slots — an input to future class-time-optimisation work (plan §16.5)."
                        });
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Outreach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHoldout")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<int>("SentBy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SentByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Outreaches");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.HasIndex("BoxId", "MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.RiskScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PChurn28d")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("SnapshotWeek")
                        .HasColumnType("date");

                    b.Property<string>("TopReasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoxId", "MemberId", "SnapshotWeek", "ModelType")
                        .IsUnique();

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.RuleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AudienceRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<int>("CooldownDaysAmber")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownDaysRed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RuleConfigs");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.WorkoutTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Tag")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutTags");
                });

            modelBuilder.Entity("BKeeper.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Alert", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.AlertEvent", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Alert", "Alert")
                        .WithMany("Events")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKeeper.Domain.Entities.ClassSession", "Session")
                        .WithMany("Bookings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ClassSession", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BKeeper.Domain.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Coach");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.EvaluationResponse", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.EvaluationForm", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Goal", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.GoalProgress", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Goal", "Goal")
                        .WithMany("Progress")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ImportRowError", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.ImportRun", "ImportRun")
                        .WithMany("RowErrors")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MemberNote", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany("Notes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Membership", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.MembershipFreeze", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Membership", "Membership")
                        .WithMany("Freezes")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Outreach", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Payment", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKeeper.Domain.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.WorkoutTag", b =>
                {
                    b.HasOne("BKeeper.Domain.Entities.Workout", "Workout")
                        .WithMany("Tags")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BKeeper.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Alert", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ClassSession", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.EvaluationForm", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Goal", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.ImportRun", b =>
                {
                    b.Navigation("RowErrors");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Member", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Memberships");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Membership", b =>
                {
                    b.Navigation("Freezes");
                });

            modelBuilder.Entity("BKeeper.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
